eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

server:
  port: 8010

spring:
  application:
    name: zuul-ws

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ribbon:
    eager-load:
      enabled: true
  sensitiveHeaders: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 99999
