server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8000/eureka


spring:
  data:
    mongodb:
      host: localhost
      database: insight_curriculum
      authentication-database: admin

  application:
    name: curriculum-ws